##########################################################################
##########################################################################
##                                       _ _    _                       ##
##             _ __ ___  _ __ __ _ _ __ (_) | _(_)                      ##
##            | '_ ` _ \| '__/ _` | '_ \| | |/ / |                      ##
##            | | | | | | | | (_| | | | | |   <| |                      ##
##            |_| |_| |_|_|  \__,_|_| |_|_|_|\_\_|                      ##
##                                                                      ##
##                                                                      ##
##               Collection for Plex-Meta-Manager                       ##
##########################################################################
##########################################################################

#   +01_ = Charts
#   +02_ = Holidays
#   +03_ = Studios or Network
#   +04_ = Collection
#   +05_ = Countries
#   +06_ = Genres
#   +07_ = Awards
#   +08_ = Decades
#   +09_ = People
#   +10_ = Movies

#####################################################
#                Genre Collections                  #
#####################################################
external_templates:
  git: PMM/templates
  template_variables:
    collection_section: "+06"

templates:
  GenreMulti:
    template: { name: GenreMulti }
    sort_title: +06_<<collection_name>>
    sync_mode: sync
    url_background: https://img5.goodfon.com/original/1920x1080/1/61/fon-netflix-logo-raduga-tsvet-fon-background-skachat-oboi-sk.jpg
    collection_order: release
    
  Genre:
    template: { name: GenreMulti }
    sort_title: +06_<<collection_name>>
    sync_mode: sync
    url_background: https://img5.goodfon.com/original/1920x1080/1/61/fon-netflix-logo-raduga-tsvet-fon-background-skachat-oboi-sk.jpg
    collection_order: custom

collections:
  Basadas en eventos verdaderos Collection:
    template: { name: GenreMulti }
    smart_label: originally_available.desc
    trakt_list: https://trakt.tv/users/manu101/lists/based-inspired-on-actual-events
    summary: Películas basadas en eventos verdaderos.

  Mindfuck Movies Collection:
    template: { name: GenreMulti }
    trakt_list:
     - https://trakt.tv/users/hdlists/lists/mindfuck-movies
     - https://trakt.tv/users/benfranklin/lists/best-mindfucks
    summary: Las siguientes películas son algunas de las películas más alucinantes jamás producidas
    url_poster: https://i.imgur.com/Tl6QMgA.png
    
  Artes Marciales Collection:
    template: { name: GenreMulti }
    imdb_list:
      - https://www.imdb.com/list/ls000099643/
      - https://www.imdb.com/list/ls068611186/
      - https://www.imdb.com/list/ls068378513/
      - https://www.imdb.com/list/ls090404120/
    summary: La película de artes marciales es un sub-género de películas de acción que cuentan con numerosas artes marciales de combate entre los personajes. Estos combates suelen ser el principal atractivo y valor de entretenimiento de las películas, y a menudo son un método de narración y expresión y desarrollo de personajes. Las artes marciales se presentan con frecuencia en escenas de entrenamiento y otras secuencias, además de peleas. Las películas de artes marciales comúnmente incluyen otros tipos de acción, como combate cuerpo a cuerpo, acrobacias, persecuciones y tiroteos.
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/genre/Martial%20Arts.jpg

  Acción Collection:
    template: { name: GenreMulti}
    trakt_list: 
      - https://trakt.tv/users/g0g0/lists/heroic-killer-bad-ass
      - https://trakt.tv/users/movistapp/lists/action
      - https://trakt.tv/users/grimreaper1972/lists/action-tv
      - https://trakt.tv/users/buzdekay/lists/action
      - https://trakt.tv/users/importimage/lists/action
    imdb_list:
      - https://www.imdb.com/search/title/?genres=action
    url_background: https://images.unsplash.com/photo-1588281345136-9893252095bd
    url_poster: https://i.imgur.com/5rP3mqc.jpg
    summary: El cine de acción es un género en el que la acción física tiene prioridad en la narración. La película a menudo tendrá movimiento continuo y acción incluyendo acrobacias físicas, persecuciones, peleas, batallas y carreras. La historia generalmente gira en torno a un héroe que tiene un objetivo, pero se enfrenta a probabilidades increíbles para obtenerlo.

  Aventura Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/fZMIfdy.jpg
    summary: El cine de aventura es un género que gira en torno a las conquistas y exploraciones de un protagonista. El propósito de la conquista puede ser recuperar una persona o un tesoro, pero a menudo el enfoque principal es simplemente la búsqueda de lo desconocido. Estas películas generalmente tienen lugar en lugares exóticos y juegan con mitos históricos. Las películas de aventura incorporan rompecabezas de suspense y obstáculos intrincados que el protagonista debe superar para lograr el objetivo final.
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/adventure
      - https://trakt.tv/users/krissykk/lists/adventure-drama-comedy-discovery-novels-1of2
 
  Animación Collection:
    template: { name: Genre}
    url_poster: https://i.imgur.com/W9355wl.jpg
    summary: La película animada es una colección de ilustraciones que se fotografían cuadro por cuadro y luego se reproducen en una rápida sucesión. Desde sus inicios, la animación ha tenido una tendencia creativa e imaginativa. Siendo capaz de traer animales y objetos a la vida, este género ha atendido a los cuentos de hadas y cuentos infantiles. Sin embargo, la animación ha sido durante mucho tiempo un género disfrutado por todas las edades. A partir de los últimos años, ha habido incluso una afluencia de animación dirigida a los adultos. La animación es comúnmente considerada como una técnica, por lo que es la capacidad de abarcar muchos géneros diferentes.
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/animation

  Comedia Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/dIMKbt9.jpg
    summary: La comedia es un género de cine que utiliza el humor como una fuerza impulsora. El objetivo de una película de comedia es la risa ilícita de la audiencia a través de historias y personajes entretenidos. Aunque la película de comedia puede tomar algún material serio, la mayoría tiene un final feliz. La comedia tiene la tendencia a convertirse en un sub-género híbrido porque el humor se puede incorporar a muchos otros géneros. Las comedias son más propensas que otras películas a recurrir al éxito y la popularidad de una estrella individual.
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/comedy
      - https://trakt.tv/users/krissykk/lists/comedy-comedy-drama
      - https://trakt.tv/users/amymarie1982/lists/comedies
      - https://trakt.tv/users/norman05/lists/sitcoms
      - https://trakt.tv/users/coldkeys/lists/classic-american-comedy
      - https://trakt.tv/users/pauls67/lists/british-comedy

  Documentales Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/KRH25hE.jpg
    summary: El cine documental es un género de no ficción destinado a documentar la realidad principalmente con fines de instrucción, educación o mantenimiento de un registro histórico.
    trakt_list: 
      - https://trakt.tv/users/hdlists/lists/documentary-movies-top-rated-from-1980-to-today
      - https://trakt.tv/users/kayaaron13/lists/ranker-greatest-documentaries-of-all-time
      - https://trakt.tv/users/sp1ti/lists/the-documentary-blog-s-top-50-documentaries-of-the-decade
      - https://trakt.tv/users/firetv4k/lists/nature-documentaries
      - https://trakt.tv/users/firetv4k/lists/science-documentaries
      - https://trakt.tv/users/michaeldibben/lists/documentaries-scientific-factual
      - https://trakt.tv/users/oxnard/lists/documentaries
      - https://trakt.tv/users/hammers-lists/lists/martial-arts-documentaries
      - https://trakt.tv/users/cscott1/lists/history-science-documentaries
      - https://trakt.tv/users/kttylttrbreath/lists/interesting-and-or-quality-documentaries

  Drama Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/RwOUFLI.jpg
    summary: El cine de Drama es un género que se basa en el desarrollo emocional y relacional de personajes realistas. Mientras que la película dramática depende en gran medida de este tipo de desarrollo, los temas dramáticos juegan un papel importante en la trama también. A menudo, estos temas dramáticos se toman de temas intensos de la vida real. Si héroes o heroínas se enfrentan a un conflicto desde el exterior o un conflicto dentro de sí mismos, la película de drama tiene como objetivo contar una historia honesta de las luchas humanas.
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/drama
      - https://trakt.tv/users/majeed_pk/lists/drama-movies-_-the-essential-list
      - https://trakt.tv/users/krissykk/lists/drama-11910764

  Distópicas Collection:
    template: { name: GenreMulti}
    trakt_list: 
      - https://trakt.tv/users/mezuror/lists/dystopian
      - https://trakt.tv/users/remontant/lists/dystopian-movies
    summary: A dystopia, or cacotopia, is a speculated ideal society with minimal crime, violence and poverty that is undesirable or frightening.

  Fantasía Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/IdeoNnr.jpg
    summary: El cine de fantasía es un género que incorpora temas imaginativos y fantásticos. Estos temas generalmente involucran magia, eventos sobrenaturales o mundos de fantasía. Aunque es su propio género, estas películas pueden coincidir con los géneros de terror y ciencia ficción. A diferencia de la ciencia ficción, una película de fantasía no necesita estar arraigada en los hechos. Este elemento permite al público ser transportado a un mundo nuevo y único. A menudo, estas películas se centran en un héroe ordinario en una situación extraordinaria.
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/fantasy
      - https://trakt.tv/users/6911557d-5846-4d10-97c8-af0ed44a5dc7/lists/fantasy
      - https://trakt.tv/users/ld667/lists/best-fantasy-movies-of-all-time

  Gangster Collection:
    template: { name: GenreMulti}
    summary: La película de gángsters es un sub-género de películas de crimen que se centra en el crimen organizado o la mafia. A menudo la trama gira en torno al ascenso y caída de un líder del crimen organizado. Muchas películas de Gangster exploran la naturaleza destructiva del crimen organizado, mientras que otras intentan mostrar la humanidad de los personajes individuales.
    trakt_list: 
      - https://trakt.tv/users/bmonomad/lists/gangster
      - https://trakt.tv/users/moses456/lists/hood_gangsters_ghetto-movies
      - https://trakt.tv/users/whitecoat21/lists/cartel-gang-mafia
      - https://trakt.tv/users/debonair-pirate/lists/mobsters
      - https://trakt.tv/users/krissykk/lists/documentary-movies-famous-gangsters-organized-crime
      - https://trakt.tv/users/majeed_pk/lists/best-mafia-gangsters-tv-shows
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/genre/Gangster.jpg

  Historia Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/1n070o0.jpg
    summary: El cine de historia es un género que toma los acontecimientos históricos y las personas y los interpreta a mayor escala. La precisión histórica no es el foco principal, sino más bien la narración de una historia grandiosa. El drama de una película de Historia a menudo se acentúa por una partitura musical arrolladora, trajes lujosos y un alto valor de producción.
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/history
      - https://trakt.tv/users/additup/lists/period-drama-history

  Musical Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/xBTTyNx.jpg
    summary: Un musical entrelaza las actuaciones vocales y de danza en la narrativa de la película. Las canciones de una película pueden usarse para promover la historia o simplemente mejorar la experiencia del público. Estas películas se hacen a menudo a gran escala e incorporan trajes y decorados lujosos. Los musicales tradicionales se centran en una estrella conocida, famosa por sus habilidades de baile o canto (p.ej. Fred Astaire, Gene Kelly, Judy Garland). Estas películas exploran conceptos tales como el amor y el éxito, lo que permite al público escapar de la realidad.
    trakt_list: 
      - https://trakt.tv/users/mpsimala/lists/musicals
      - https://trakt.tv/users/guavalove/lists/musical-television
      - https://trakt.tv/users/trakker/lists/musical-tv
      - https://trakt.tv/users/asterlea/lists/top-musicals
      - https://trakt.tv/users/maxwelldeux/lists/bfi-s-100-film-musicals

  Romance Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/0Jm9Jck.jpg
    summary: "El cine romántico puede definirse como un género en el que la trama gira en torno al amor entre dos protagonistas. Este género generalmente tiene un tema que explora un tema dentro del amor, incluyendo pero no limitado a: amor a primera vista, amor prohibido, triángulos de amor y amor sacrificial. El tono de la película Romance puede variar mucho. Ya sea que el final sea feliz o trágico, la película Romance tiene como objetivo evocar emociones fuertes en el público."
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/romance
      - https://trakt.tv/users/rdjones247/lists/films-romance
      - https://trakt.tv/users/krissykk/lists/romance-comedy-and-drama-mixed-movies?sort=title,asc
 
  Sci-Fi Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/EPi451Z.jpg
    summary: La película de ciencia ficción (Sci-Fi) es un género que incorpora temas hipotéticos y basados en la ciencia en la trama de la película. A menudo, este género incorpora elementos y tecnologías futuristas para explorar cuestiones sociales, políticas y filosóficas. La película en sí se desarrolla generalmente en el futuro, ya sea en la tierra o en el espacio. Tradicionalmente, una película de ciencia ficción incorporará héroes, villanos, lugares inexplorados, misiones fantásticas y tecnología avanzada.
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/science-fiction
      - https://trakt.tv/users/canconfirm/lists/sci-fi
      - https://trakt.tv/users/chazlarson/lists/looper-best-scifi-of-2021
      - https://trakt.tv/users/evilbyte/lists/hard-science-fiction
      - https://trakt.tv/users/zapin/lists/best-sci-fi-series

  Deportes Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/uGtTbYV.jpg
    summary: Una película deportiva gira en torno a un entorno deportivo, un evento o un atleta. A menudo, estas películas se centrarán en un único evento deportivo que tiene una importancia significativa. Las películas deportivas tradicionalmente tienen una trama simple que se acumula hasta el evento deportivo significativo. Este género es conocido por incorporar técnicas cinematográficas para construir anticipación e intensidad. Las películas deportivas tienen una amplia gama de sub-géneros, desde comedias hasta dramas, y son más propensas que otros géneros a estar basadas en eventos de la vida real.
    trakt_list: 
      - https://trakt.tv/users/lish408/lists/sports-documentary-series-film

  Guerra Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/tPgvWij.jpg
    summary: War Film es un género que analiza la realidad de la guerra a gran escala. A menudo se centran en batallas históricas, así como en cuestiones políticas dentro de la guerra. Este género por lo general se centra en un personaje principal y su equipo de apoyo, dando a la audiencia una mirada al interior de la cruda realidad de la guerra.
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/war
      - https://trakt.tv/users/maxtrontv/lists/war-tv-shows
      - https://trakt.tv/users/majeed_pk/lists/wwii-tv-series
      - https://trakt.tv/users/debonair-pirate/lists/war
      - https://trakt.tv/users/majeed_pk/lists/wwii-tv-series
      - https://trakt.tv/users/jonatos1972/lists/war

  Western Collection:
    template: { name: GenreMulti}
    url_poster: https://i.imgur.com/NbiRkV6.jpg
    summary: "Western Film es un género que gira en torno a historias ambientadas principalmente a finales del siglo XIX en el Viejo Oeste estadounidense. La mayoría de los westerns se sitúan entre la Guerra Civil Americana (1865) y los primeros años 1900. Los temas comunes en Western Film incluyen: la conquista del salvaje oeste, la separación cultural de Oriente y Occidente, la resistencia de Occidente al cambio moderno, el conflicto entre vaqueros e indios, forajidos y la caza de tesoros/ oro. American Western Film generalmente gira en torno a un héroe estoico y enfatiza la importancia del honor y el sacrificio."
    trakt_list: 
      - https://trakt.tv/users/kayaaron13/lists/ranker-top-western-movies
      - https://trakt.tv/users/movistapp/lists/western
      - https://trakt.tv/users/bambos/lists/western-tv-series-watchlist
      - https://trakt.tv/users/artscience84/lists/cowboy-hat
      - https://trakt.tv/users/kodiuser000000/lists/tv-westerns
    
  Zombie Collection:
    template: { name: GenreMulti}
    trakt_list: 
      - https://trakt.tv/users/ld667/lists/the-most-epic-zombie-films-since-2000
      - https://trakt.tv/users/almj24/lists/zombies
      - https://trakt.tv/users/mraniki/lists/zombie

  Terror Collection:
    template: { name: GenreMulti}
    trakt_list: 
      - https://trakt.tv/users/marcelocastanheira/lists/slashers
      - https://trakt.tv/users/dough13/lists/slashers
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/genre/Slasher.jpg












