##########################################################################
##########################################################################
##                                       _ _    _                       ##
##             _ __ ___  _ __ __ _ _ __ (_) | _(_)                      ##
##            | '_ ` _ \| '__/ _` | '_ \| | |/ / |                      ##
##            | | | | | | | | (_| | | | | |   <| |                      ##
##            |_| |_| |_|_|  \__,_|_| |_|_|_|\_\_|                      ##
##                                                                      ##
##                                                                      ##
##               Collection for Plex-Meta-Manager                       ##
##########################################################################
##########################################################################

#   +01_ = Charts
#   +02_ = Holidays
#   +03_ = Studios or Network
#   +04_ = Collection
#   +05_ = Countries
#   +06_ = Genres
#   +07_ = Awards
#   +08_ = Decades
#   +09_ = People
#   +10_ = Movies

#####################################################
#                Genre Collections                  #
#####################################################
external_templates:
  git: PMM/templates
  template_variables:
    collection_section: "+03"

templates:
  GenreMulti:
    template: { name: GenreMulti }
    sort_title: +01_<<collection_name>>
    sync_mode: sync
    url_background: https://img5.goodfon.com/original/1920x1080/1/61/fon-netflix-logo-raduga-tsvet-fon-background-skachat-oboi-sk.jpg
    collection_order: release
    
  Genre:
    template: { name: GenreMulti }
    sort_title: +03_<<collection_name>>
    sync_mode: sync
    url_background: https://img5.goodfon.com/original/1920x1080/1/61/fon-netflix-logo-raduga-tsvet-fon-background-skachat-oboi-sk.jpg
    collection_order: custom

collections:
  80's y 90's Collection:
    template: { name: GenreMulti }
    trakt_list: https://trakt.tv/users/hdlists/lists/nostalgiac-movies-from-the-80s-90s
    summary: Todas las películas nostálgicas de los años 80 y 90 en una colección
    url_poster: https://i.imgur.com/vE8dsdd.jpg
    url_background: https://i.imgur.com/frz0kly.jpg

  2000's Collection:
    template: { name: GenreMulti }
    trakt_list: https://trakt.tv/users/hdlists/lists/best-of-the-00s
    summary: Las mejores peliculas de la primera década del siglo 
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/decade/2000.jpg

  2010's Collection:
    template: { name: GenreMulti }
    trakt_list: https://trakt.tv/users/hdlists/lists/best-of-the-2010s
    summary: Las mejores peliculas de la década del 2010
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/decade/2010.jpg

  2020 Collection:
    template: { name: GenreMulti }
    trakt_list: https://trakt.tv/users/hdlists/lists/most-popular-movies-of-2020
    summary: Las mejores peliculas del año 2020
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/year/best/2020.jpg

  2021 Collection:
    template: { name: GenreMulti }
    trakt_list: https://trakt.tv/users/hdlists/lists/2021-best-rated-movies-so-far
    summary: Las mejores peliculas del año 2021
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/year/best/2021.jpg

  2022 Collection:
    template: { name: GenreMulti }
    trakt_list: https://trakt.tv/users/echophil/lists/2022
    summary: Los estrenos del 2022
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/year/2022.jpg









